export const restaurantDataList = [
  {
    info: {
      id: "628118",
      name: "Hotel Dawath",
      cloudinaryImageId: "hpooldauljohuiap84a8",
      locality: "Narveer Tanaji Wadi",
      areaName: "Shivajinagar",
      costForTwo: "₹200 for two",
      cuisines: ["Indian", "Chinese", "Beverages"],
      avgRating: 3,
      parentId: "98713",
      avgRatingString: "3.0",
      totalRatingsString: "50+",
      sla: { 
        cost : 250 ,
        deliveryTime: 23,
        lastMileTravel: 1.6,
        serviceability: "SERVICEABLE",
        slaString: "23 mins",
        lastMileTravelString: "1.6 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
  {
    info: {
      id: "456986",
      name: "Domino's Pizza",
      cloudinaryImageId: "clcpnrfs8dz1xcrlbhwr",
      locality: "Somwar Peth",
      areaName: "Rasta Peth",
      costForTwo: "₹400 for two",
      cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
      avgRating: 4.1,
      parentId: "2456",
      avgRatingString: "4.1",
      totalRatingsString: "500+",
      sla: { 
        cost : 400 ,
        deliveryTime: 25,
        serviceability: "SERVICEABLE",
        slaString: "25 mins",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
  {
    info: {
      id: "243625",
      name: "KFC",
      cloudinaryImageId: "f01666ac73626461d7455d9c24005cd4",
      locality: "Deccan Gymkhana",
      areaName: "Deccan Gymkhana",
      costForTwo: "₹400 for two",
      cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
      avgRating: 4.1,
      parentId: "547",
      avgRatingString: "4.1",
      totalRatingsString: "1K+",
      sla: { 
        cost : 200 ,
        deliveryTime: 19,
        lastMileTravel: 2.2,
        serviceability: "SERVICEABLE",
        slaString: "19 mins",
        lastMileTravelString: "2.2 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
  {
    info: {
      id: "506982",
      name: "McDonald's",
      cloudinaryImageId: "bb7ae131544c7d37e10fc5faf76f09d6",
      locality: "Narayan Peth",
      areaName: "Shaniwar Peth",
      costForTwo: "₹400 for two",
      cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
      avgRating: 4.4,
      parentId: "630",
      avgRatingString: "4.4",
      totalRatingsString: "1K+",
      sla: { 
        cost : 100 ,
        deliveryTime: 22,
        lastMileTravel: 1.3,
        serviceability: "SERVICEABLE",
        slaString: "22 mins",
        lastMileTravelString: "1.3 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
  {
    info: {
      id: "768373",
      name: "Samudra Veg",
      cloudinaryImageId: "e18e58b3bbd76ee7e61bd8b41f4c3d3e",
      locality: "Sarasbaug",
      areaName: "Swargate",
      costForTwo: "₹500 for two",
      cuisines: ["Indian"],
      avgRating: 4.4,
      veg: true,
      parentId: "176775",
      avgRatingString: "4.4",
      totalRatingsString: "50+",
      sla: { 
        cost : 300 ,
        deliveryTime: 25,
        lastMileTravel: 2.4,
        serviceability: "SERVICEABLE",
        slaString: "25 mins",
        lastMileTravelString: "2.4 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
  {
    info: {
      id: "42581",
      name: "Burger King",
      cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
      locality: "The Pavillion Mall",
      areaName: "Shivajinagar",
      costForTwo: "₹350 for two",
      cuisines: ["Burgers", "American"],
      avgRating: 4.1,
      parentId: "166",
      avgRatingString: "4.1",
      totalRatingsString: "10K+",
      sla: { 
        cost : 200 ,
        deliveryTime: 33,
        lastMileTravel: 4.8,
        serviceability: "SERVICEABLE",
        slaString: "33 mins",
        lastMileTravelString: "4.8 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
  {
    info: {
      id: "20058",
      name: "SP's Biryani House",
      cloudinaryImageId: "b2jeywla2n5b8h25ey1p",
      locality: "Sadashiv Peth",
      areaName: "Sadashiv Peth",
      costForTwo: "₹900 for two",
      cuisines: ["Biryani", "North Indian", "Indian", "Maharashtrian"],
      avgRating: 4.3,
      parentId: "192891",
      avgRatingString: "4.3",
      totalRatingsString: "10K+",
      sla: { 
        cost : 400 ,
        deliveryTime: 25,
        lastMileTravel: 1.9,
        serviceability: "SERVICEABLE",
        slaString: "25 mins",
        lastMileTravelString: "1.9 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
  {
    info: {
      id: "602068",
      name: "Filli Bites",
      cloudinaryImageId: "mrx9cr6gmscdoz3xeugm",
      locality: "Cantonment Board",
      areaName: "Camp Area",
      costForTwo: "₹300 for two",
      cuisines: ["Fast Food", "American", "Lebanese"],
      avgRating: 4.5,
      parentId: "79406",
      avgRatingString: "4.5",
      totalRatingsString: "100+",
      sla: { 
        cost : 200 ,
        deliveryTime: 34,
        lastMileTravel: 2.4,
        serviceability: "SERVICEABLE",
        slaString: "34 mins",
        lastMileTravelString: "2.4 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
  {
    info: {
      id: "34715",
      name: "Kok Pa Chinese",
      cloudinaryImageId: "gvvdbegf1guwzww6rsbh",
      locality: "FC Road",
      areaName: "Shivaji Nagar",
      costForTwo: "₹250 for two",
      cuisines: ["Chinese", "Asian"],
      avgRating: 4.2,
      parentId: "18863",
      avgRatingString: "4.2",
      totalRatingsString: "5K+",
      sla: { 
        cost : 300 ,
        deliveryTime: 19,
        lastMileTravel: 2,
        serviceability: "SERVICEABLE",
        slaString: "19 mins",
        lastMileTravelString: "2.0 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  },
  {
    info: {
      id: "47633",
      name: "The Belgian Waffle Co.",
      cloudinaryImageId: "5116a385bac0548e06c33c08350fbf11",
      locality: "Kumud Nagar",
      areaName: "Goregaon West",
      costForTwo: "₹200 for two",
      cuisines: ["Waffle","Desserts","Ice Cream","Beverages"],
      avgRating: 4.6,
      veg: true,
      parentId: "2233",
      avgRatingString: "4.6",
      totalRatingsString: "5K+",
      sla: { 
        cost : 100 ,
        deliveryTime: 28
      }
    },
  },
    {
    info: {
      id: "332613",
      name: "Charcoal Eats - Biryani & Beyond",
      cloudinaryImageId: "d796c32a336dcce6814de6921d916966",
      locality: "Balaji International School",
      areaName: "Malad West",
      costForTwo: "₹499 for two",
      cuisines: ["Biryani","Kebabs","Hyderabadi" ],
      avgRating: 4.3,
      parentId: "5338",
      avgRatingString: "4.3",
      totalRatingsString: "1K+",
      sla: { 
        cost : 200 ,
        deliveryTime: 22,
        
      },
    },
  
  },
      {
    info: {
      id: "10446",
      name: "5 Spice",
      cloudinaryImageId: "gjweg0kfstoxlxlhklcn",
      locality: "New Link Road",
      areaName: "Malad Kan West",
      costForTwo: "₹750 for two",
      cuisines: ["Chinese","Asian","Thai","Seafood"],
      avgRating: 4.1,
      sla: { 
        cost : 400 ,
        deliveryTime: 25,
      },
    },
  },
  {
    info: {
      id: "10447",
      name: "Khana Khazana",
      cloudinaryImageId: "gvvdbegf1guwzww6rsbh",
      locality: "New Link Road",
      areaName: "Malad Kan West",
      costForTwo: "₹750 for two",
      cuisines: ["Chinese","Asian","Thai","Seafood"],
      avgRating: 3.4,
      sla: { 
        cost : 500 ,
        deliveryTime: 40,
      },
    },
  }
];