export const restaurantDataList = [
    {
      info: {
        id: "628118",
        name: "Hotel Dawath",
        cloudinaryImageId: "hpooldauljohuiap84a8",
        locality: "Narveer Tanaji Wadi",
        areaName: "Shivajinagar",
        costForTwo: "₹200 for two",
        cuisines: ["Indian", "Chinese", "Beverages"],
        avgRating: 3,
        parentId: "98713",
        avgRatingString: "3.0",
        totalRatingsString: "50+",
        sla: {
          deliveryTime: 23,
          lastMileTravel: 1.6,
          serviceability: "SERVICEABLE",
          slaString: "23 mins",
          lastMileTravelString: "1.6 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-07 23:30:00",
          opened: true,
        },
      },
    },
    {
      info: {
        id: "456986",
        name: "Domino's Pizza",
        cloudinaryImageId: "clcpnrfs8dz1xcrlbhwr",
        locality: "Somwar Peth",
        areaName: "Rasta Peth",
        costForTwo: "₹400 for two",
        cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
        avgRating: 4.1,
        parentId: "2456",
        avgRatingString: "4.1",
        totalRatingsString: "500+",
        sla: {
          deliveryTime: 25,
          serviceability: "SERVICEABLE",
          slaString: "25 mins",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-07 23:59:00",
          opened: true,
        },
      },
    },
    {
      info: {
        id: "243625",
        name: "KFC",
        cloudinaryImageId: "f01666ac73626461d7455d9c24005cd4",
        locality: "Deccan Gymkhana",
        areaName: "Deccan Gymkhana",
        costForTwo: "₹400 for two",
        cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
        avgRating: 4.1,
        parentId: "547",
        avgRatingString: "4.1",
        totalRatingsString: "1K+",
        sla: {
          deliveryTime: 19,
          lastMileTravel: 2.2,
          serviceability: "SERVICEABLE",
          slaString: "19 mins",
          lastMileTravelString: "2.2 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-08 02:00:00",
          opened: true,
        },
      },
    },
    {
      info: {
        id: "506982",
        name: "McDonald's",
        cloudinaryImageId: "bb7ae131544c7d37e10fc5faf76f09d6",
        locality: "Narayan Peth",
        areaName: "Shaniwar Peth",
        costForTwo: "₹400 for two",
        cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
        avgRating: 4.4,
        parentId: "630",
        avgRatingString: "4.4",
        totalRatingsString: "1K+",
        sla: {
          deliveryTime: 22,
          lastMileTravel: 1.3,
          serviceability: "SERVICEABLE",
          slaString: "22 mins",
          lastMileTravelString: "1.3 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-07 23:45:00",
          opened: true,
        },
      },
    },
    {
      info: {
        id: "768373",
        name: "Samudra Veg",
        cloudinaryImageId: "e18e58b3bbd76ee7e61bd8b41f4c3d3e",
        locality: "Sarasbaug",
        areaName: "Swargate",
        costForTwo: "₹500 for two",
        cuisines: ["Indian"],
        avgRating: 4.4,
        veg: true,
        parentId: "176775",
        avgRatingString: "4.4",
        totalRatingsString: "50+",
        sla: {
          deliveryTime: 25,
          lastMileTravel: 2.4,
          serviceability: "SERVICEABLE",
          slaString: "25 mins",
          lastMileTravelString: "2.4 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-07 23:00:00",
          opened: true,
        },
      },
    },
    {
      info: {
        id: "42581",
        name: "Burger King",
        cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
        locality: "The Pavillion Mall",
        areaName: "Shivajinagar",
        costForTwo: "₹350 for two",
        cuisines: ["Burgers", "American"],
        avgRating: 4.1,
        parentId: "166",
        avgRatingString: "4.1",
        totalRatingsString: "10K+",
        sla: {
          deliveryTime: 33,
          lastMileTravel: 4.8,
          serviceability: "SERVICEABLE",
          slaString: "33 mins",
          lastMileTravelString: "4.8 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-08 02:00:00",
          opened: true,
        },
      },
    },
    {
      info: {
        id: "20058",
        name: "SP's Biryani House",
        cloudinaryImageId: "b2jeywla2n5b8h25ey1p",
        locality: "Sadashiv Peth",
        areaName: "Sadashiv Peth",
        costForTwo: "₹900 for two",
        cuisines: ["Biryani", "North Indian", "Indian", "Maharashtrian"],
        avgRating: 4.3,
        parentId: "192891",
        avgRatingString: "4.3",
        totalRatingsString: "10K+",
        sla: {
          deliveryTime: 25,
          lastMileTravel: 1.9,
          serviceability: "SERVICEABLE",
          slaString: "25 mins",
          lastMileTravelString: "1.9 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-07 14:55:00",
          opened: true,
        },
      },
    },
    {
      info: {
        id: "602068",
        name: "Filli Bites",
        cloudinaryImageId: "mrx9cr6gmscdoz3xeugm",
        locality: "Cantonment Board",
        areaName: "Camp Area",
        costForTwo: "₹300 for two",
        cuisines: ["Fast Food", "American", "Lebanese"],
        avgRating: 4.5,
        parentId: "79406",
        avgRatingString: "4.5",
        totalRatingsString: "100+",
        sla: {
          deliveryTime: 34,
          lastMileTravel: 2.4,
          serviceability: "SERVICEABLE",
          slaString: "34 mins",
          lastMileTravelString: "2.4 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-07 23:30:00",
          opened: true,
        },
      },
    },
    {
      info: {
        id: "34715",
        name: "Kok Pa Chinese",
        cloudinaryImageId: "gvvdbegf1guwzww6rsbh",
        locality: "FC Road",
        areaName: "Shivaji Nagar",
        costForTwo: "₹250 for two",
        cuisines: ["Chinese", "Asian"],
        avgRating: 4.2,
        parentId: "18863",
        avgRatingString: "4.2",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 19,
          lastMileTravel: 2,
          serviceability: "SERVICEABLE",
          slaString: "19 mins",
          lastMileTravelString: "2.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-01-07 23:57:00",
          opened: true,
        },
      },
    },
    
  ];